name: anime_ui
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: 9.1.0
  flutter_bloc: 9.1.1
  get_it: 9.2.0
  rxdart: 0.28.0
  cached_network_image:
  anime_api:
    path: ../api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0