name: chat_api
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.3

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
