name: chat_ui
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  chat_api:
    path: ../api
  bloc:
  flutter_bloc:
  get_it:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^9.1.5
  mocktail: ^1.0.3