name: chat_impl
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  dio: 5.9.0
  get_it: 9.2.0
  pretty_dio_logger: 1.4.0
  rxdart: 0.28.0
  chat_api:
    path: ../api

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  http_mock_adapter: ^0.6.1
