name: todo_impl
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  dio: 5.9.0
  get_it: 9.2.0
  hive: 2.2.3
  connectivity_plus: 7.0.0
  hive_flutter: 1.1.0
  path_provider: 2.1.2
  pretty_dio_logger: 1.4.0
  rxdart: 0.28.0
  todo_api:
    path: ../api

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
